### PR TITLE
Sassdoc integration

### PR DESCRIPTION
**Pull request by lcalvino**
Integrate Sassdoc, comment all sections in a Sassdoc format and tweak some styles, mixins and functions

-Task 'doc' added with 'connect:server' & 'watch' tasks. Usage: 'grunt doc'
-function 'to-list' removed from _functions.scss beacuse it's already in sassy-cast.
-function 'bp-calculation' removed because is no longer used.
-Create a mixin for 'c-accordion' component
-Create a mixin for 'c-alert' component
-Create a mixin for 'c-modal' component
-Create a mixin for 'c-rating' component and fix the before content, now is no longer hardcoded.
-Create a mixin for 'c-tabs' component.

Usage: 
run `grunt doc` in terminal
open `http://localhost:1337/sassdoc` in the browser

### CODE REVIEW

**Comment by arzafran** [comment]
Looks good to me bro! 
This is a major step up in producing a nice pile of code, and knowing what it does! :)

:+1:  great job!

**Comment by damianmuti** [comment]
Great job, @lcalvino !
I'm so glad we finally have some documentation!

My 2 cents:
* Include dev/sassdoc folder into .gitignore; there's no reason to have docs source code in the repo.
* Since we cannot have multi-level menu (Components/Acordions, Alerts, etc), it would be great to rename those @group keys with something like Component - Accordions, Component - Alerts and so on.

Kudos, buddy!

**Comment by damianmuti** [comment]
Looks great now!
Go merge it! :100:

**Comment by lcalvino** [comment]
#merged

**Pull request merged**
